In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("PyTorch version: ", torch.__version__)

PyTorch version:  2.3.1


## Introduction to Tensors

### Creating tensors  
PyTorch tensors are created using the `torch.tensor()` function  
https://pytorch.org/docs/stable/tensors.html  
| Name | What is it | Number of dimensions | Lower or Upper |
|------|------------|----------------------|----------------|
| Scalar | Single number | 0 | lower(a) |
| Vector | Sequence of numbers | 1 | lower(y) |
| Matrix | a 2-dimensional array of numbers | 2 | upper(Q) |
| Tensor | a n-dimensional array of numbers | can be any number<br>a 0-dimension is a scalar<br>a 1-dimension is a tensor<br>a 2-dimension is a matrix | upper(X) |


In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 7], [9, 10]])
MATRIX

tensor([[ 7,  7],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[7, 7],
                        [9, 10]],
                        [[11, 12],
                         [13, 14]]])
TENSOR

tensor([[[ 7,  7],
         [ 9, 10]],

        [[11, 12],
         [13, 14]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 2, 2])

### Random tensors
Why random tensors?  

Random tensors are important, because the way many nural networks is that they start with tensors in random numbers and then adjust those random numbers to better represent the data.  
`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [15]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8421, 0.3380, 0.8048, 0.4464],
        [0.8613, 0.3388, 0.3622, 0.9429],
        [0.0942, 0.5098, 0.4320, 0.2108]])

In [16]:
# create a random tensor with the similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, color_channels (RGB)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [17]:
# Create a tensor of a zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
# Create a tensor of ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensor-like

In [19]:
# Use torch.arange() to create a tensor with range of values
one_to_ten = torch.arange(start=0, end=11, step=2)
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10])

In [20]:
# Creating tensors like
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensors datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:  
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [21]:
# Float 32 tensor
float_32_tensor = torch.tensor([1, 2, 3], 
                                dtype=None, # What data is the tensor (e.g. float32, float64, etc)
                                device=None, # What device is the tensor on (CPU, GPU)
                                requires_grad=False) # Whether you want to calculate gradients with the tensor operations
float_32_tensor

tensor([1, 2, 3])

In [22]:
float_16_tensor = torch.tensor([1, 2, 3], dtype=torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [23]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.], dtype=torch.float16)

In [24]:
int_32_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
int_32_tensor

tensor([1, 2, 3], dtype=torch.int32)

### Getting information from Tensors (Attributes)
  
1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [25]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6636, 0.1335, 0.1312, 0.5223],
        [0.0970, 0.0603, 0.8986, 0.2296],
        [0.9450, 0.0193, 0.3059, 0.4715]])

In [26]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")
print(f"Shape of tensor: {some_tensor.shape}")

tensor([[0.6636, 0.1335, 0.1312, 0.5223],
        [0.0970, 0.0603, 0.8986, 0.2296],
        [0.9450, 0.0193, 0.3059, 0.4715]])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Shape of tensor: torch.Size([3, 4])


### Manipulating Tensors (tensors operations)

Tensors operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [27]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [28]:
# Multiply tensor by ten
tensor * 10

tensor([10, 20, 30])

In [29]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [30]:
# Try out PyTorch inbuild functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication

Two ways of performing multiplication in neural networks and Deep Learning:  
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathisfun.com/algebra/matrix-multiplying.html  

There are two main rules that performing matrix multiplication needs to satisfy:
1. the **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(2, 3) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2) -> (2, 2)`
* `(3, 2) @ (2, 3) -> (3, 3)`

In [31]:
# Element wise multiplication
print(tensor, "*" ,tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [32]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [33]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [34]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 395 μs, sys: 572 μs, total: 967 μs
Wall time: 983 μs


In [35]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 53 μs, sys: 17 μs, total: 70 μs
Wall time: 68.7 μs


tensor(14)

### One of the most common errors in Deep Learning

In [36]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                          [3, 4],
                          [5, 6]])
tensor_B = torch.tensor([[7, 8],
                          [9, 10],
                          [11, 12]])
print(tensor_A.shape, tensor_B.shape)
torch.matmul(tensor_A, tensor_B)

torch.Size([3, 2]) torch.Size([3, 2])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issue, we can manipulate the shape of one of our tensors using a **transpose**  
A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"Output shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:
tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean
# torch.mean(x.float()), x.float().mean()
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

### Finding the positional min and max

In [ ]:
x
x.argmin(), x.argmax()

(tensor(0), tensor(9))

## Reshaping, stacking, sqeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [47]:
# Create a tensor
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [56]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [57]:
# change the view
z = x.view(1, 9)
z, z.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [58]:
# Changing z changes x, because a view of a tensor shares the same memory as the original tensor
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [68]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [76]:
# torch.squeeze() removes all the axes with length 1
print(f"Previous tensor: {x_reshaped}")
print(f"Squeezed tensor: {x_reshaped.shape}")

# Remove extra dimensions
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Squeezed tensor: torch.Size([1, 9])
New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New Shape: torch.Size([9])


In [70]:
x_reshaped.shape

torch.Size([1, 9])

In [71]:
x_reshaped.squeeze()

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
x_reshaped.squeeze().shape

torch.Size([9])

In [79]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimention)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])
New tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
New shape: torch.Size([1, 9])


In [83]:
# torch.permute() - rearranges the original tensor according to the desired ordering and returns a new multidimensional rotated tensor
x_original = torch.rand(224, 224, 3) # height, width, color_channels (RGB)

# permute the tensor dimensions
x_permuted = x_original.permute(2, 0, 1)
print(f"Original shape: {x_original.shape}")
print(f"Permuted shape: {x_permuted.shape}")

Original shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with pytorch is similar with Numpy

In [91]:
# create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [86]:
# Lets index the tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [87]:
# Lets index the middle element (dim=1)
x[0][0]

tensor([1, 2, 3])

In [88]:
# Lets index the last element (dim=2)
x[0][0][0]

tensor(1)

In [93]:
x[0][2][2]

tensor(9)

In [94]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [96]:
# Get all values of the 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [98]:
# Get all values of the 0 dimension but only index 1 of 1st and 2nd dimension, but only the 1st index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [99]:
# Get index 0 of 0th and 1st dimension, but all values of the 2nd dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])