In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("PyTorch version: ", torch.__version__)

PyTorch version:  2.3.1


## Introduction to Tensors

### Creating tensors  
PyTorch tensors are created using the `torch.tensor()` function  
https://pytorch.org/docs/stable/tensors.html  
| Name | What is it | Number of dimensions | Lower or Upper |
|------|------------|----------------------|----------------|
| Scalar | Single number | 0 | lower(a) |
| Vector | Sequence of numbers | 1 | lower(y) |
| Matrix | a 2-dimensional array of numbers | 2 | upper(Q) |
| Tensor | a n-dimensional array of numbers | can be any number<br>a 0-dimension is a scalar<br>a 1-dimension is a tensor<br>a 2-dimension is a matrix | upper(X) |


In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 7], [9, 10]])
MATRIX

tensor([[ 7,  7],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[7, 7],
                        [9, 10]],
                        [[11, 12],
                         [13, 14]]])
TENSOR

tensor([[[ 7,  7],
         [ 9, 10]],

        [[11, 12],
         [13, 14]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([2, 2, 2])

### Random tensors
Why random tensors?  

Random tensors are important, because the way many nural networks is that they start with tensors in random numbers and then adjust those random numbers to better represent the data.  
`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8385, 0.7867, 0.5139, 0.6973],
        [0.5469, 0.8425, 0.9537, 0.0079],
        [0.7203, 0.0712, 0.9024, 0.5581]])

In [17]:
# create a random tensor with the similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, color_channels (RGB)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [18]:
# Create a tensor of a zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
# Create a tensor of ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensor-like

In [22]:
# Use torch.arange() to create a tensor with range of values
one_to_ten = torch.arange(start=0, end=11, step=2)
one_to_ten

tensor([ 0,  2,  4,  6,  8, 10])

In [24]:
# Creating tensors like
ten_zeroes = torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0])