In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("PyTorch version: ", torch.__version__)

PyTorch version:  2.3.1


## Introduction to Tensors

### Creating tensors  
PyTorch tensors are created using the `torch.tensor()` function  
https://pytorch.org/docs/stable/tensors.html  
| Name | What is it | Number of dimensions | Lower or Upper |
|------|------------|----------------------|----------------|
| Scalar | Single number | 0 | lower(a) |
| Vector | Sequence of numbers | 1 | lower(y) |
| Matrix | a 2-dimensional array of numbers | 2 | upper(Q) |
| Tensor | a n-dimensional array of numbers | can be any number<br>a 0-dimension is a scalar<br>a 1-dimension is a tensor<br>a 2-dimension is a matrix | upper(X) |


In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 7], [9, 10]])
MATRIX

tensor([[ 7,  7],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[7, 7],
                        [9, 10]],
                        [[11, 12],
                         [13, 14]]])
TENSOR

tensor([[[ 7,  7],
         [ 9, 10]],

        [[11, 12],
         [13, 14]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([2, 2, 2])